extends SceneTree

func _initialize() -> void:
	var scene := load("res://scenes/Main.tscn")
	assert(scene != null)
	var root: Node = scene.instantiate()
	assert(root != null)
	assert(root.fleets.is_empty())
	root._seed_stars()
	root._fleets_setup()
	assert(root.fleets.size() == 5)
	assert(root._formation_offsets("횡진", 28).size() == 28)
	assert(root._formation_offsets("쐐기진", 24).size() == 24)
	assert(root._formation_offsets("방진", 26).size() == 26)
	assert(root.fleets[0].ships == 28)
	root._set_formation(root.fleets[0], "방진")
	assert(root.fleets[0].formation == "방진")
	assert(root.fleets[0].formation_from == "횡진")
	assert(root._visual_formation_offsets(root.fleets[0]).size() == 28)
	root._issue_salvo(0, 3)
	assert(root.salvo_source == 0)
	assert(root.salvo_target == 3)
	assert(is_equal_approx(root.fleets[3].shield, 0.48))
	assert(root._ship_class_index("F01", 0) == 0)
	assert(root._ship_class_index("A01", 0) == 3)
	assert(root._ship_class_index("E01", 0) == 2)
	assert(root._ship_class_index("F01", 3) == 8)
	assert(root._ship_class_index("F01", 13) == 4)
	assert(root._ship_class_source_rect(0).size.x > 1000.0)
	assert(root._ship_class_source_rect(9) == Rect2(1448, 0, 724, 724))
	assert(root._vfx_source_rect(0) == Rect2(0, 0, 440, 440))
	assert(root._vfx_source_rect(7) == Rect2(1320, 440, 440, 440))
	print("VISIBLE_FLEET_POC_SMOKE_PASS")
	quit(0)
